services:
  mysql-server:
    image: mysql:8.0
    container_name: itop-db
    restart: always  
    command:
      - mysqld
      - --port=3306  
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=2000
      - --mysqlx_max_connections=2000   
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
      - MYSQL_ROOT_PASSWORD=root_pwd

  application:
    image: jackywn/itop:latest
    container_name : itop-www
    restart: always    
    ports:
      - "8000:80"
    volumes:
      - ./itop:/app 
    environment:
      - VERSION_itop=3.0.1
      - PHP_DATE_TIMEZONE=Asia/Shanghai
      - PHP_POST_MAX_SIZE=100M 
